kind = "web"
previewPath = "/"
title = "Hekayaty Awards 2026"
version = "1.0.0"
id = "artifacts/hekayaty"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19646

[services.development]
run = "pnpm --filter @workspace/hekayaty run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hekayaty", "run", "build" ]
serve = "static"
publicDir = "artifacts/hekayaty/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19646"
BASE_PATH = "/"
